// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-9vIdFfVyi3Pd9OfizU4TUqANpuRFV_k',
    appId: '1:412444903210:web:44a152bf4cf4066037c053',
    messagingSenderId: '412444903210',
    projectId: 'benji-rider',
    authDomain: 'benji-rider.firebaseapp.com',
    storageBucket: 'benji-rider.appspot.com',
    measurementId: 'G-7D8G465PDL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeh7EOibu1oSvrwOJ5B_nYfHFYy8ALPYs',
    appId: '1:412444903210:ios:ed4b25e67f7cafc537c053',
    messagingSenderId: '412444903210',
    projectId: 'benji-rider',
    storageBucket: 'benji-rider.appspot.com',
    iosBundleId: 'com.benjiexpress.rider.ios',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZofdP5ESaJI360BW02unpEHj_BLm-3Nc',
    appId: '1:412444903210:android:fde0991e344a702637c053',
    messagingSenderId: '412444903210',
    projectId: 'benji-rider',
    storageBucket: 'benji-rider.appspot.com',
  );
}
